In [25]:
import pandas as pd

In [67]:
df = pd.read_csv("GDL-AreaData421.csv")

C:\Users\riley\AppData\Local\Temp\ipykernel_10164\1046735981.py:1: DtypeWarning: Columns (16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,68,76,79,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,189,192,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,245) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\riley\\OneDrive\\Desktop\\Urban Developing Omdena\\GDL-AreaData421.csv")

In [68]:
df.head()

,iso_code,ISO2,iso_num,country,year,datasource,GDLCODE,level,region,continent,...,npopold,npipedwater,nelectr,nflushtoilet,nsmallhouse,nmodsizehouse,nlargehouse,nnaturalfloor,ncookwood,empty
0,AFG,AF,4,Afghanistan,2010,MICS,AFGt,National,Total,Asia/Pacific,...,101710,13116,13112,13116,12651,12651,12651,13116,13089,0
1,AFG,AF,4,Afghanistan,2010,MICS,AFGtr,Urb/rur,Rural,Asia/Pacific,...,83711,10689,10685,10689,10291,10291,10291,10689,10664,0
2,AFG,AF,4,Afghanistan,2010,MICS,AFGtu,Urb/rur,Urban,Asia/Pacific,...,17999,2427,2427,2427,2360,2360,2360,2427,2425,0
3,AFG,AF,4,Afghanistan,2010,MICS,AFGp0,Poverty,Nonpoor,Asia/Pacific,...,35385,4166,4164,4166,4071,4071,4071,4166,4163,0
4,AFG,AF,4,Afghanistan,2010,MICS,AFGp1,Poverty,Poor,Asia/Pacific,...,66323,8950,8948,8950,8580,8580,8580,8950,8925,0

In [69]:
african_countries = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cameroon', 'Central African Republic (CAR)', 'Chad', 'Comoros', 'Democratic Republic of the Congo', 'Republic of the Congo', 'Cote d\'Ivoire', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini (formerly Swaziland)', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe']

In [70]:
df = df[df['country'].isin(african_countries)]

In [71]:
df.head()

,iso_code,ISO2,iso_num,country,year,datasource,GDLCODE,level,region,continent,...,npopold,npipedwater,nelectr,nflushtoilet,nsmallhouse,nmodsizehouse,nlargehouse,nnaturalfloor,ncookwood,empty
34,AGO,AO,24,Angola,2000,MICS,AGOt,National,Total,Africa,...,30117,6250,6250,6248,6250,6250,6250,6250,,0
35,AGO,AO,24,Angola,2000,MICS,AGOtr,Urb/rur,Rural,Africa,...,9104,2134,2134,2131,2134,2134,2134,2134,,0
36,AGO,AO,24,Angola,2000,MICS,AGOtu,Urb/rur,Urban,Africa,...,21013,4116,4116,4116,4116,4116,4116,4116,,0
37,AGO,AO,24,Angola,2000,MICS,AGOp0,Poverty,Nonpoor,Africa,...,4941,770,770,770,770,770,770,770,,0
38,AGO,AO,24,Angola,2000,MICS,AGOp1,Poverty,Poor,Africa,...,25168,5481,5481,5478,5481,5481,5481,5481,,0

In [72]:
df.isnull().sum()/len(df)

iso_code         0.000000
ISO2             0.021999
iso_num          0.000000
country          0.000000
year             0.000000
                   ...
nmodsizehouse    0.000000
nlargehouse      0.000000
nnaturalfloor    0.000000
ncookwood        0.000000
empty            0.000000
Length: 252, dtype: float64

In [73]:
df.to_csv("GDL-AreaData421_preprocessed.csv")