In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('Top-20_population-count_2000-2020_part2.csv')

In [24]:
df

,latitude,longitude,Adjusted-Population-Count_2000,Adjusted-Population-Count_2005,Adjusted-Population-Count_2010,Adjusted-Population-Count_2015,Adjusted-Population-Count_2020,Data-Code_2010,Data-Quality_Data-Context_2010,Data-Quality_Mean-Administrative-Unit-Area_2010,Data-Quality_Water-Mask_2010,Growth-Rate-End-Year_2010,Growth-Rate-Start-Year_2010,Growth_Rate-Admin-Level_2010,Input-Data-Age_2010,Input-Data-Level_2010,Input-Data-Sex_2010,Input-Data-Year_2010,Land-Area_2010,National-Identifier-Grid_2010,Water-Area_2010,Year-most-recent-Census_2010,Country_Name
0,2.645833,39.354167,52.883865,81.955950,127.009964,196.83173,305.03693,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
1,2.645833,39.395833,52.883865,81.955950,127.009964,196.83173,305.03693,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
2,2.645833,39.437500,52.883865,81.955950,127.009964,196.83173,305.03693,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
3,2.645833,39.479167,53.407093,82.766815,128.266590,198.77916,308.05493,1.0,0.0,510.775240,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
4,2.645833,39.520833,67.086586,103.966400,161.120320,249.69373,386.95898,1.0,0.0,450.969880,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319079,35.895833,-5.520833,137.373500,136.233150,135.102260,133.98076,132.86858,1.0,0.0,89.804720,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,1.253216,504.0,1.535794,2014.0,Morocco
319080,35.895833,-5.479167,1171.346400,1161.622900,1151.980200,1142.41750,1132.93410,1.0,0.0,96.100464,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,11.569997,504.0,3.489163,2014.0,Morocco
319081,35.895833,-5.437500,990.175960,1017.042500,1052.197900,1097.63840,1155.84470,1.0,0.0,117.491910,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,14.321472,504.0,2.378894,2014.0,Morocco
319082,35.895833,-5.395833,8078.852500,9038.036000,10150.755000,11447.86400,12967.19300,1.0,0.0,31.404121,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,16.062042,504.0,1.366061,2014.0,Morocco
319083,35.937500,-5.395833,65.061386,76.171280,89.599815,105.87913,125.66803,1.0,0.0,23.659704,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,0.357336,504.0,1.733376,2014.0,Morocco

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319084 entries, 0 to 319083
Data columns (total 23 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   latitude                                         319084 non-null  float64
 1   longitude                                        319084 non-null  float64
 2   Adjusted-Population-Count_2000                   318719 non-null  float64
 3   Adjusted-Population-Count_2005                   318719 non-null  float64
 4   Adjusted-Population-Count_2010                   318719 non-null  float64
 5   Adjusted-Population-Count_2015                   318719 non-null  float64
 6   Adjusted-Population-Count_2020                   318719 non-null  float64
 7   Data-Code_2010                                   319084 non-null  float64
 8   Data-Quality_Data-Context_2010                   318719 non-null  float64
 9   Data-Quality_Mean-Administrative-Unit-Area_2010  319084 non-null  float64
 10  Data-Quality_Water-Mask_2010                     319084 non-null  float64
 11  Growth-Rate-End-Year_2010                        319084 non-null  float64
 12  Growth-Rate-Start-Year_2010                      319084 non-null  float64
 13  Growth_Rate-Admin-Level_2010                     319084 non-null  float64
 14  Input-Data-Age_2010                              319084 non-null  float64
 15  Input-Data-Level_2010                            319084 non-null  float64
 16  Input-Data-Sex_2010                              319084 non-null  float64
 17  Input-Data-Year_2010                             319084 non-null  float64
 18  Land-Area_2010                                   319084 non-null  float64
 19  National-Identifier-Grid_2010                    319084 non-null  float64
 20  Water-Area_2010                                  319084 non-null  float64
 21  Year-most-recent-Census_2010                     319084 non-null  float64
 22  Country_Name                                     319084 non-null  object
dtypes: float64(22), object(1)
memory usage: 56.0+ MB

In [26]:
df.describe()

,latitude,longitude,Adjusted-Population-Count_2000,Adjusted-Population-Count_2005,Adjusted-Population-Count_2010,Adjusted-Population-Count_2015,Adjusted-Population-Count_2020,Data-Code_2010,Data-Quality_Data-Context_2010,Data-Quality_Mean-Administrative-Unit-Area_2010,Data-Quality_Water-Mask_2010,Growth-Rate-End-Year_2010,Growth-Rate-Start-Year_2010,Growth_Rate-Admin-Level_2010,Input-Data-Age_2010,Input-Data-Level_2010,Input-Data-Sex_2010,Input-Data-Year_2010,Land-Area_2010,National-Identifier-Grid_2010,Water-Area_2010,Year-most-recent-Census_2010
count,319084.000000,319084.000000,318719.000000,3.187190e+05,3.187190e+05,3.187190e+05,3.187190e+05,319084.000000,318719.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000,319084.000000
mean,14.946180,23.115141,1044.117577,1.183667e+03,1.346269e+03,1.536809e+03,1.761881e+03,1.222011,26.464456,32719.113138,1.964621,2008.771631,1996.039613,1.230792,1.488028,2.439781,2.306574,2007.780274,20.345863,535.970403,0.139360,2006.714624
std,8.759913,14.830329,6416.580990,7.088646e+03,7.886139e+03,8.848003e+03,1.005464e+04,1.029936,68.737624,55749.465508,0.192529,2.768300,5.780451,0.522609,1.217351,0.679313,0.833122,2.495577,1.954873,239.842636,1.291536,5.495423
min,2.645833,-13.145833,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000,0.000000,0.000000,2005.000000,1987.000000,1.000000,0.000000,2.000000,0.000000,2005.000000,0.000000,120.000000,0.000000,1984.000000
25%,7.854167,11.437500,28.580874,3.144089e+01,3.772712e+01,4.772913e+01,5.859080e+01,1.000000,0.000000,1867.217700,2.000000,2007.000000,1993.000000,1.000000,0.000000,2.000000,2.000000,2006.000000,19.932692,231.000000,0.000000,2006.000000
50%,12.520833,27.854167,198.790270,2.239072e+02,2.611831e+02,2.990633e+02,3.432198e+02,1.000000,0.000000,8561.804000,2.000000,2008.000000,1994.000000,1.000000,2.000000,2.000000,2.000000,2007.000000,20.978262,566.000000,0.000000,2007.000000
75%,21.395833,34.187500,794.177770,9.143447e+02,1.050275e+03,1.208789e+03,1.381393e+03,1.000000,0.000000,34927.590000,2.000000,2012.000000,1999.000000,1.000000,2.000000,3.000000,3.000000,2008.000000,21.301287,729.000000,0.000000,2008.000000
max,35.937500,47.937500,963072.900000,1.003478e+06,1.046297e+06,1.091724e+06,1.172177e+06,6.000000,205.000000,224454.660000,2.000000,2014.000000,2006.000000,3.000000,3.000000,5.000000,5.000000,2014.000000,21.491003,818.000000,21.490276,2014.000000

In [27]:
pd.options.display.max_columns = None

In [28]:
df

,latitude,longitude,Adjusted-Population-Count_2000,Adjusted-Population-Count_2005,Adjusted-Population-Count_2010,Adjusted-Population-Count_2015,Adjusted-Population-Count_2020,Data-Code_2010,Data-Quality_Data-Context_2010,Data-Quality_Mean-Administrative-Unit-Area_2010,Data-Quality_Water-Mask_2010,Growth-Rate-End-Year_2010,Growth-Rate-Start-Year_2010,Growth_Rate-Admin-Level_2010,Input-Data-Age_2010,Input-Data-Level_2010,Input-Data-Sex_2010,Input-Data-Year_2010,Land-Area_2010,National-Identifier-Grid_2010,Water-Area_2010,Year-most-recent-Census_2010,Country_Name
0,2.645833,39.354167,52.883865,81.955950,127.009964,196.83173,305.03693,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
1,2.645833,39.395833,52.883865,81.955950,127.009964,196.83173,305.03693,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
2,2.645833,39.437500,52.883865,81.955950,127.009964,196.83173,305.03693,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
3,2.645833,39.479167,53.407093,82.766815,128.266590,198.77916,308.05493,1.0,0.0,510.775240,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
4,2.645833,39.520833,67.086586,103.966400,161.120320,249.69373,386.95898,1.0,0.0,450.969880,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319079,35.895833,-5.520833,137.373500,136.233150,135.102260,133.98076,132.86858,1.0,0.0,89.804720,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,1.253216,504.0,1.535794,2014.0,Morocco
319080,35.895833,-5.479167,1171.346400,1161.622900,1151.980200,1142.41750,1132.93410,1.0,0.0,96.100464,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,11.569997,504.0,3.489163,2014.0,Morocco
319081,35.895833,-5.437500,990.175960,1017.042500,1052.197900,1097.63840,1155.84470,1.0,0.0,117.491910,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,14.321472,504.0,2.378894,2014.0,Morocco
319082,35.895833,-5.395833,8078.852500,9038.036000,10150.755000,11447.86400,12967.19300,1.0,0.0,31.404121,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,16.062042,504.0,1.366061,2014.0,Morocco
319083,35.937500,-5.395833,65.061386,76.171280,89.599815,105.87913,125.66803,1.0,0.0,23.659704,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,0.357336,504.0,1.733376,2014.0,Morocco

### Handling Missing Values

In [29]:
df.isna().sum()

latitude                                             0
longitude                                            0
Adjusted-Population-Count_2000                     365
Adjusted-Population-Count_2005                     365
Adjusted-Population-Count_2010                     365
Adjusted-Population-Count_2015                     365
Adjusted-Population-Count_2020                     365
Data-Code_2010                                       0
Data-Quality_Data-Context_2010                     365
Data-Quality_Mean-Administrative-Unit-Area_2010      0
Data-Quality_Water-Mask_2010                         0
Growth-Rate-End-Year_2010                            0
Growth-Rate-Start-Year_2010                          0
Growth_Rate-Admin-Level_2010                         0
Input-Data-Age_2010                                  0
Input-Data-Level_2010                                0
Input-Data-Sex_2010                                  0
Input-Data-Year_2010                                 0
Land-Area_2010                                       0
National-Identifier-Grid_2010                        0
Water-Area_2010                                      0
Year-most-recent-Census_2010                         0
Country_Name                                         0
dtype: int64

In [30]:
df_corr = df.corr()

In [31]:
df_corr['Adjusted-Population-Count_2000'].sort_values(ascending=False)

Adjusted-Population-Count_2000                     1.000000
Adjusted-Population-Count_2005                     0.998408
Adjusted-Population-Count_2010                     0.993291
Adjusted-Population-Count_2015                     0.983403
Adjusted-Population-Count_2020                     0.964990
Input-Data-Age_2010                                0.068200
Water-Area_2010                                    0.018684
Year-most-recent-Census_2010                       0.012371
Input-Data-Sex_2010                                0.009575
latitude                                           0.002572
Growth-Rate-Start-Year_2010                       -0.000410
Growth_Rate-Admin-Level_2010                      -0.001010
National-Identifier-Grid_2010                     -0.005848
Growth-Rate-End-Year_2010                         -0.011628
Input-Data-Level_2010                             -0.012373
Land-Area_2010                                    -0.023298
Input-Data-Year_2010                              -0.025251
Data-Code_2010                                    -0.026440
longitude                                         -0.053763
Data-Quality_Data-Context_2010                    -0.062649
Data-Quality_Water-Mask_2010                      -0.072442
Data-Quality_Mean-Administrative-Unit-Area_2010   -0.088949
Name: Adjusted-Population-Count_2000, dtype: float64

In [32]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [33]:
missing_data = df.isna()
imputer = IterativeImputer()

In [34]:
imputed_data = imputer.fit_transform(df[['Adjusted-Population-Count_2000','Adjusted-Population-Count_2005','Adjusted-Population-Count_2010','Adjusted-Population-Count_2015','Adjusted-Population-Count_2020']])

In [35]:
imputed_data_df = pd.DataFrame(imputed_data, columns=df.columns[2:7])
imputed_missing_data = imputed_data_df.isna()
imputed_missing_data.sum()

Adjusted-Population-Count_2000    0
Adjusted-Population-Count_2005    0
Adjusted-Population-Count_2010    0
Adjusted-Population-Count_2015    0
Adjusted-Population-Count_2020    0
dtype: int64

In [36]:
imputed_data_df

,Adjusted-Population-Count_2000,Adjusted-Population-Count_2005,Adjusted-Population-Count_2010,Adjusted-Population-Count_2015,Adjusted-Population-Count_2020
0,52.883865,81.955950,127.009964,196.83173,305.03693
1,52.883865,81.955950,127.009964,196.83173,305.03693
2,52.883865,81.955950,127.009964,196.83173,305.03693
3,53.407093,82.766815,128.266590,198.77916,308.05493
4,67.086586,103.966400,161.120320,249.69373,386.95898
...,...,...,...,...,...
319079,137.373500,136.233150,135.102260,133.98076,132.86858
319080,1171.346400,1161.622900,1151.980200,1142.41750,1132.93410
319081,990.175960,1017.042500,1052.197900,1097.63840,1155.84470
319082,8078.852500,9038.036000,10150.755000,11447.86400,12967.19300
319083,65.061386,76.171280,89.599815,105.87913,125.66803

In [40]:
exclude_cols = ['Adjusted-Population-Count_2000', 'Adjusted-Population-Count_2005', 'Adjusted-Population-Count_2010', 'Adjusted-Population-Count_2015', 'Adjusted-Population-Count_2020']
df = df.loc[:, ~df.columns.isin(exclude_cols)]

In [41]:
df

,latitude,longitude,Data-Code_2010,Data-Quality_Data-Context_2010,Data-Quality_Mean-Administrative-Unit-Area_2010,Data-Quality_Water-Mask_2010,Growth-Rate-End-Year_2010,Growth-Rate-Start-Year_2010,Growth_Rate-Admin-Level_2010,Input-Data-Age_2010,Input-Data-Level_2010,Input-Data-Sex_2010,Input-Data-Year_2010,Land-Area_2010,National-Identifier-Grid_2010,Water-Area_2010,Year-most-recent-Census_2010,Country_Name
0,2.645833,39.354167,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
1,2.645833,39.395833,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
2,2.645833,39.437500,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
3,2.645833,39.479167,1.0,0.0,510.775240,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
4,2.645833,39.520833,1.0,0.0,450.969880,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319079,35.895833,-5.520833,1.0,0.0,89.804720,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,1.253216,504.0,1.535794,2014.0,Morocco
319080,35.895833,-5.479167,1.0,0.0,96.100464,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,11.569997,504.0,3.489163,2014.0,Morocco
319081,35.895833,-5.437500,1.0,0.0,117.491910,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,14.321472,504.0,2.378894,2014.0,Morocco
319082,35.895833,-5.395833,1.0,0.0,31.404121,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,16.062042,504.0,1.366061,2014.0,Morocco
319083,35.937500,-5.395833,1.0,0.0,23.659704,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,0.357336,504.0,1.733376,2014.0,Morocco

In [42]:
df = pd.concat([df,imputed_data_df],axis=1)

In [43]:
df

,latitude,longitude,Data-Code_2010,Data-Quality_Data-Context_2010,Data-Quality_Mean-Administrative-Unit-Area_2010,Data-Quality_Water-Mask_2010,Growth-Rate-End-Year_2010,Growth-Rate-Start-Year_2010,Growth_Rate-Admin-Level_2010,Input-Data-Age_2010,Input-Data-Level_2010,Input-Data-Sex_2010,Input-Data-Year_2010,Land-Area_2010,National-Identifier-Grid_2010,Water-Area_2010,Year-most-recent-Census_2010,Country_Name,Adjusted-Population-Count_2000,Adjusted-Population-Count_2005,Adjusted-Population-Count_2010,Adjusted-Population-Count_2015,Adjusted-Population-Count_2020
0,2.645833,39.354167,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,52.883865,81.955950,127.009964,196.83173,305.03693
1,2.645833,39.395833,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,52.883865,81.955950,127.009964,196.83173,305.03693
2,2.645833,39.437500,1.0,0.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,52.883865,81.955950,127.009964,196.83173,305.03693
3,2.645833,39.479167,1.0,0.0,510.775240,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,53.407093,82.766815,128.266590,198.77916,308.05493
4,2.645833,39.520833,1.0,0.0,450.969880,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,67.086586,103.966400,161.120320,249.69373,386.95898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319079,35.895833,-5.520833,1.0,0.0,89.804720,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,1.253216,504.0,1.535794,2014.0,Morocco,137.373500,136.233150,135.102260,133.98076,132.86858
319080,35.895833,-5.479167,1.0,0.0,96.100464,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,11.569997,504.0,3.489163,2014.0,Morocco,1171.346400,1161.622900,1151.980200,1142.41750,1132.93410
319081,35.895833,-5.437500,1.0,0.0,117.491910,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,14.321472,504.0,2.378894,2014.0,Morocco,990.175960,1017.042500,1052.197900,1097.63840,1155.84470
319082,35.895833,-5.395833,1.0,0.0,31.404121,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,16.062042,504.0,1.366061,2014.0,Morocco,8078.852500,9038.036000,10150.755000,11447.86400,12967.19300
319083,35.937500,-5.395833,1.0,0.0,23.659704,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,0.357336,504.0,1.733376,2014.0,Morocco,65.061386,76.171280,89.599815,105.87913,125.66803

In [44]:
df['Data-Quality_Data-Context_2010'].unique()

array([  0., 205.,  nan])

In [45]:
df = df.drop(columns=['Data-Quality_Data-Context_2010'],axis=1)

In [46]:
df

,latitude,longitude,Data-Code_2010,Data-Quality_Mean-Administrative-Unit-Area_2010,Data-Quality_Water-Mask_2010,Growth-Rate-End-Year_2010,Growth-Rate-Start-Year_2010,Growth_Rate-Admin-Level_2010,Input-Data-Age_2010,Input-Data-Level_2010,Input-Data-Sex_2010,Input-Data-Year_2010,Land-Area_2010,National-Identifier-Grid_2010,Water-Area_2010,Year-most-recent-Census_2010,Country_Name,Adjusted-Population-Count_2000,Adjusted-Population-Count_2005,Adjusted-Population-Count_2010,Adjusted-Population-Count_2015,Adjusted-Population-Count_2020
0,2.645833,39.354167,1.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,52.883865,81.955950,127.009964,196.83173,305.03693
1,2.645833,39.395833,1.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,52.883865,81.955950,127.009964,196.83173,305.03693
2,2.645833,39.437500,1.0,514.947700,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,52.883865,81.955950,127.009964,196.83173,305.03693
3,2.645833,39.479167,1.0,510.775240,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,53.407093,82.766815,128.266590,198.77916,308.05493
4,2.645833,39.520833,1.0,450.969880,2.0,2009.0,1999.0,1.0,2.0,5.0,5.0,2009.0,21.491003,404.0,0.000000,2009.0,Kenya,67.086586,103.966400,161.120320,249.69373,386.95898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319079,35.895833,-5.520833,1.0,89.804720,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,1.253216,504.0,1.535794,2014.0,Morocco,137.373500,136.233150,135.102260,133.98076,132.86858
319080,35.895833,-5.479167,1.0,96.100464,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,11.569997,504.0,3.489163,2014.0,Morocco,1171.346400,1161.622900,1151.980200,1142.41750,1132.93410
319081,35.895833,-5.437500,1.0,117.491910,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,14.321472,504.0,2.378894,2014.0,Morocco,990.175960,1017.042500,1052.197900,1097.63840,1155.84470
319082,35.895833,-5.395833,1.0,31.404121,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,16.062042,504.0,1.366061,2014.0,Morocco,8078.852500,9038.036000,10150.755000,11447.86400,12967.19300
319083,35.937500,-5.395833,1.0,23.659704,1.0,2014.0,2004.0,2.0,3.0,3.0,3.0,2014.0,0.357336,504.0,1.733376,2014.0,Morocco,65.061386,76.171280,89.599815,105.87913,125.66803