In [240]:
import pandas as pd

In [241]:
df = pd.read_csv('un_compiled_housing_data_africa.csv')

In [242]:
df

,"United Nations, Department of Economic and Social Affairs\nPopulation Division",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HOUSEHOLD SIZE AND COMPOSITION 2022\n\n\nCopyr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,Households by size\n(percentage ),NaN,NaN,NaN,NaN,Households by age of the head of household (pe...,NaN,NaN,NaN,Households with at least one member in age ran...,NaN,NaN,NaN,NaN,Households with members in age ranges\n(percen...,NaN,NaN,NaN,NaN,NaN,Average number of household members of selecte...,NaN,NaN,NaN,NaN,Basic household types (percentage of household...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Intergenerational household types (percentage ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of househ...,Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at le...,Under age 20 years among all households,Under age 20 years among households with at le...,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation,Skip generation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,24,MICS,07-01-01,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,United Republic of Tanzania,834,DHS,15/12/2007,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,0.000,49.76,22.66,17.78,6.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,United Republic of Tanzania,834,DHS,03-06-10,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,0.03,47.09,23.56,17.76,5.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,United Republic of Tanzania,834,DHS,29/02/2012,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,0.0,47.76,24.99,19.88,5.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,United Republic of Tanzania,834,IPUMS,07-01-12,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,0.0,44.62,20.83,13.35,4.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,United Republic of Tanzania,834,DHS,17/11/2015,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,0.0,48.33,22.64,17.68,5.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Drop columns and change column names

In [243]:
df = df.drop(labels=range(0,3))

In [244]:
df = df.reset_index()

In [245]:
df

,index,"United Nations, Department of Economic and Social Affairs\nPopulation Division",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133
0,3,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of househ...,Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at le...,Under age 20 years among all households,Under age 20 years among households with at le...,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation,Skip generation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,Angola,24,MICS,07-01-01,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Angola,24,DHS,29/01/2007,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,0.1,47.25,27.86,20.52,3.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6,Angola,24,DHS,03-01-11,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,0.03,57.79,20.83,16.02,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,Angola,24,DHS,01-01-16,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,0.01,54.81,17.54,13.34,3.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,111,United Republic of Tanzania,834,DHS,15/12/2007,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,0.000,49.76,22.66,17.78,6.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,112,United Republic of Tanzania,834,DHS,03-06-10,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,0.03,47.09,23.56,17.76,5.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,113,United Republic of Tanzania,834,DHS,29/02/2012,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,0.0,47.76,24.99,19.88,5.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,114,United Republic of Tanzania,834,IPUMS,07-01-12,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,0.0,44.62,20.83,13.35,4.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,115,United Republic of Tanzania,834,DHS,17/11/2015,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,0.0,48.33,22.64,17.68,5.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [246]:
pd.options.display.max_columns = None
(df)

,index,"United Nations, Department of Economic and Social Affairs\nPopulation Division",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133
0,3,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of househ...,Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at le...,Under age 20 years among all households,Under age 20 years among households with at le...,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation,Skip generation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,Angola,24,MICS,07-01-01,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Angola,24,DHS,29/01/2007,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,0.1,47.25,27.86,20.52,3.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6,Angola,24,DHS,03-01-11,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,0.03,57.79,20.83,16.02,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,Angola,24,DHS,01-01-16,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,0.01,54.81,17.54,13.34,3.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,111,United Republic of Tanzania,834,DHS,15/12/2007,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,0.000,49.76,22.66,17.78,6.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,112,United Republic of Tanzania,834,DHS,03-06-10,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,0.03,47.09,23.56,17.76,5.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,113,United Republic of Tanzania,834,DHS,29/02/2012,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,0.0,47.76,24.99,19.88,5.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,114,United Republic of Tanzania,834,IPUMS,07-01-12,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,0.0,44.62,20.83,13.35,4.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,115,United Republic of Tanzania,834,DHS,17/11/2015,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,0.0,48.33,22.64,17.68,5.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [247]:
df = df.drop(df.columns[43:], axis=1)

In [248]:
df

,index,"United Nations, Department of Economic and Social Affairs\nPopulation Division",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41
0,3,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of househ...,Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at le...,Under age 20 years among all households,Under age 20 years among households with at le...,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation
1,4,Angola,24,MICS,07-01-01,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..,..
2,5,Angola,24,DHS,29/01/2007,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,0.1,47.25,27.86,20.52
3,6,Angola,24,DHS,03-01-11,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,0.03,57.79,20.83,16.02
4,7,Angola,24,DHS,01-01-16,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,0.01,54.81,17.54,13.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,111,United Republic of Tanzania,834,DHS,15/12/2007,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,0.000,49.76,22.66,17.78
109,112,United Republic of Tanzania,834,DHS,03-06-10,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,0.03,47.09,23.56,17.76
110,113,United Republic of Tanzania,834,DHS,29/02/2012,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,0.0,47.76,24.99,19.88
111,114,United Republic of Tanzania,834,IPUMS,07-01-12,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,0.0,44.62,20.83,13.35
112,115,United Republic of Tanzania,834,DHS,17/11/2015,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,0.0,48.33,22.64,17.68

In [249]:
new_header = df.iloc[0] 
df = df[1:] 
df.columns = new_header

In [250]:
df

,3,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at least one member under age 15 years,Under age 20 years among all households,Under age 20 years among households with at least one member under age 20 years,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation
1,4,Angola,24,MICS,07-01-01,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..,..
2,5,Angola,24,DHS,29/01/2007,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,0.1,47.25,27.86,20.52
3,6,Angola,24,DHS,03-01-11,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,0.03,57.79,20.83,16.02
4,7,Angola,24,DHS,01-01-16,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,0.01,54.81,17.54,13.34
5,8,Cameroon,120,IPUMS,07-01-76,5.07,13.18,28.27,22.32,36.22,13.79,1.78,88.21,15.64,9.75,66.26,70.43,72.98,23.59,15.81,14.55,9.68,15.31,10.2,15.62,10.4,2.21,3.33,2.69,3.68,2.19,13.18,9.17,21.85,4.86,3.61,1.25,40.57,10.08,0.28,35.88,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,111,United Republic of Tanzania,834,DHS,15/12/2007,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,0.000,49.76,22.66,17.78
109,112,United Republic of Tanzania,834,DHS,03-06-10,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,0.03,47.09,23.56,17.76
110,113,United Republic of Tanzania,834,DHS,29/02/2012,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,0.0,47.76,24.99,19.88
111,114,United Republic of Tanzania,834,IPUMS,07-01-12,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,0.0,44.62,20.83,13.35
112,115,United Republic of Tanzania,834,DHS,17/11/2015,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,0.0,48.33,22.64,17.68

In [251]:
df = df.drop(columns=[3],axis=1)

In [252]:
df

,Country or area,ISO Code,Data source category,Reference date (dd/mm/yyyy),Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at least one member under age 15 years,Under age 20 years among all households,Under age 20 years among households with at least one member under age 20 years,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Unknown,Nuclear,Multi-generation,Three generation
1,Angola,24,MICS,07-01-01,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..,..
2,Angola,24,DHS,29/01/2007,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,0.1,47.25,27.86,20.52
3,Angola,24,DHS,03-01-11,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,0.03,57.79,20.83,16.02
4,Angola,24,DHS,01-01-16,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,0.01,54.81,17.54,13.34
5,Cameroon,120,IPUMS,07-01-76,5.07,13.18,28.27,22.32,36.22,13.79,1.78,88.21,15.64,9.75,66.26,70.43,72.98,23.59,15.81,14.55,9.68,15.31,10.2,15.62,10.4,2.21,3.33,2.69,3.68,2.19,13.18,9.17,21.85,4.86,3.61,1.25,40.57,10.08,0.28,35.88,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,United Republic of Tanzania,834,DHS,15/12/2007,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,0.000,49.76,22.66,17.78
109,United Republic of Tanzania,834,DHS,03-06-10,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,0.03,47.09,23.56,17.76
110,United Republic of Tanzania,834,DHS,29/02/2012,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,0.0,47.76,24.99,19.88
111,United Republic of Tanzania,834,IPUMS,07-01-12,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,0.0,44.62,20.83,13.35
112,United Republic of Tanzania,834,DHS,17/11/2015,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,0.0,48.33,22.64,17.68

In [253]:
df = df.drop(columns=['ISO Code','Data source category','Reference date (dd/mm/yyyy)','Unknown'],axis=1)

In [254]:
df

,Country or area,Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at least one member under age 15 years,Under age 20 years among all households,Under age 20 years among households with at least one member under age 20 years,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Nuclear,Multi-generation,Three generation
1,Angola,4.75,7.91,26.39,31.19,34.5,..,..,..,..,..,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,..,..,..,..,..,..,..,..,..,..,..
2,Angola,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,47.25,27.86,20.52
3,Angola,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,57.79,20.83,16.02
4,Angola,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,54.81,17.54,13.34
5,Cameroon,5.07,13.18,28.27,22.32,36.22,13.79,1.78,88.21,15.64,9.75,66.26,70.43,72.98,23.59,15.81,14.55,9.68,15.31,10.2,15.62,10.4,2.21,3.33,2.69,3.68,2.19,13.18,9.17,21.85,4.86,3.61,1.25,40.57,10.08,35.88,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,United Republic of Tanzania,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,49.76,22.66,17.78
109,United Republic of Tanzania,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,47.09,23.56,17.76
110,United Republic of Tanzania,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,47.76,24.99,19.88
111,United Republic of Tanzania,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,44.62,20.83,13.35
112,United Republic of Tanzania,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,48.33,22.64,17.68

### Change dtype

In [255]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 1 to 112
Data columns (total 38 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Country or area                                                                  112 non-null    object
 1   Average household size (number of members)                                       112 non-null    object
 2   1 member                                                                         112 non-null    object
 3   2-3 members                                                                      112 non-null    object
 4   4-5 members                                                                      112 non-null    object
 5   6 or more members                                                                112 non-null    object
 6   Female head of household (percentage of households)                              112 non-null    object
 7   Under 20 years (aged 0-19)                                                       112 non-null    object
 8   Aged 20-64 years                                                                 112 non-null    object
 9   Aged 60 years or over                                                            112 non-null    object
 10  Aged 65 years or over                                                            112 non-null    object
 11  Under 15 years (aged 0-14)                                                       112 non-null    object
 12  Under 18 years (aged 0-17)                                                       112 non-null    object
 13  Under 20 years (aged 0-19)                                                       112 non-null    object
 14  Aged 60 years or over                                                            112 non-null    object
 15  Aged 65 years or over                                                            112 non-null    object
 16  Under 15 years AND 60 years or over                                              112 non-null    object
 17  Under 15 years AND 65 years or over                                              112 non-null    object
 18  Under 18 years AND 60 years or over                                              112 non-null    object
 19  Under 18 years AND 65 years or over                                              112 non-null    object
 20  Under 20 years AND 60 years or over                                              112 non-null    object
 21  Under 20 years AND 65 years or over                                              112 non-null    object
 22  Under age 15 years among all households                                          112 non-null    object
 23  Under age 15 years among households with at least one member under age 15 years  112 non-null    object
 24  Under age 20 years among all households                                          112 non-null    object
 25  Under age 20 years among households with at least one member under age 20 years  112 non-null    object
 26  Ages 20-64 years among all households                                            112 non-null    object
 27  One-person                                                                       112 non-null    object
 28  Couple only                                                                      112 non-null    object
 29  Couple with children                                                             112 non-null    object
 30  Single parent with children                                                      112 non-null    object
 31  Single mother with children                                                      112 non-null    object
 32  Single father with children                                                      112 non-null    object
 33  Extended family                                                                  112 non-null    object
 34  Non-relatives                                                                    112 non-null    object
 35  Nuclear                                                                          112 non-null    object
 36  Multi-generation                                                                 112 non-null    object
 37  Three generation                                                                 112 non-null    object
dtypes: object(38)
memory usage: 33.4+ KB

In [256]:
import numpy as np

In [257]:
def remove_dot(dataset,columns,dot):
    dataset[columns] = dataset[columns].replace(dot,np.nan)

In [258]:
remove_dot(df,'Female head of household (percentage of households)','..')
remove_dot(df,'Under 20 years (aged 0-19)','..')
remove_dot(df,'Aged 20-64 years','..')
remove_dot(df,'Aged 60 years or over','..')
remove_dot(df,'Aged 65 years or over','..')
remove_dot(df,'One-person','..')
remove_dot(df,'Couple only','..')
remove_dot(df,'Couple with children','..')
remove_dot(df,'Single parent with children','..')
remove_dot(df,'Single mother with children','..')
remove_dot(df,'Single father with children','..')
remove_dot(df,'Extended family','..')
remove_dot(df,'Non-relatives','..')
remove_dot(df,'Nuclear','..')
remove_dot(df,'Multi-generation','..')
remove_dot(df,'Three generation','..')
remove_dot(df,'Average household size (number of members)','..')
remove_dot(df,'1 member','..')
remove_dot(df,'2-3 members','..')
remove_dot(df,'4-5 members','..')
remove_dot(df,'6 or more members','..')
remove_dot(df,'Under 15 years (aged 0-14)','..')
remove_dot(df,'Under 18 years (aged 0-17)','..')
remove_dot(df,'Under 20 years (aged 0-19)','..')
remove_dot(df,'Aged 60 years or over','..')
remove_dot(df,'Aged 65 years or over','..')
remove_dot(df,'Under 15 years AND 60 years or over','..')
remove_dot(df,'Under 15 years AND 65 years or over','..')
remove_dot(df,'Under 18 years AND 60 years or over','..')
remove_dot(df,'Under 18 years AND 65 years or over','..')
remove_dot(df,'Under 20 years AND 60 years or over','..')
remove_dot(df,'Under 20 years AND 65 years or over','..')
remove_dot(df,'Under age 15 years among all households','..')
remove_dot(df,'Under age 15 years among households with at least one member under age 15 years','..')
remove_dot(df,'Under age 20 years among all households','..')
remove_dot(df,'Under age 20 years among households with at least one member under age 20 years','..')
remove_dot(df,'Ages 20-64 years among all households','..')

In [259]:
df

,Country or area,Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at least one member under age 15 years,Under age 20 years among all households,Under age 20 years among households with at least one member under age 20 years,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Nuclear,Multi-generation,Three generation
1,Angola,4.75,7.91,26.39,31.19,34.5,NaN,NaN,NaN,NaN,NaN,81.02,83.83,85.89,13.96,8.78,8.34,5,9,5.38,9.24,5.49,2.3,2.84,2.81,3.27,1.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,5.69,4.08,19.1,30.13,46.69,24.78,1.74,89.1,14.85,8.79,84.6,87.84,89.21,19.48,12.6,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.7,2.23,4.08,4.33,36.35,6.58,5.6,0.97,47.85,0.72,47.25,27.86,20.52
3,Angola,4.98,6.6,22.84,32.79,37.77,21.74,1.36,90.82,13.01,7.6,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2,6.6,5.35,45.01,7.43,6.22,1.21,35.03,0.55,57.79,20.83,16.02
4,Angola,4.82,10.81,23.9,28.46,36.83,34.47,1.85,88.4,12.85,7.88,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.34,36.08,13.39,12.14,1.25,32.8,1.57,54.81,17.54,13.34
5,Cameroon,5.07,13.18,28.27,22.32,36.22,13.79,1.78,88.21,15.64,9.75,66.26,70.43,72.98,23.59,15.81,14.55,9.68,15.31,10.2,15.62,10.4,2.21,3.33,2.69,3.68,2.19,13.18,9.17,21.85,4.86,3.61,1.25,40.57,10.08,35.88,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,United Republic of Tanzania,4.99,7.92,25.13,30.01,36.95,24.43,0.57,85.03,20.1,14.26,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.5,2.33,2.93,2.81,3.34,1.96,7.92,5.81,35.49,8.45,7.45,1,36.24,6.09,49.76,22.66,17.78
109,United Republic of Tanzania,4.97,8.53,24.89,30.66,35.92,24.4,0.91,84.51,20.58,14.56,79.14,82.45,84.19,24.97,18.51,17.47,12.7,18.65,13.57,19.16,13.96,2.3,2.9,2.79,3.31,1.96,8.53,4.71,34.02,8.36,6.58,1.77,37.57,6.78,47.09,23.56,17.76
110,United Republic of Tanzania,5.12,8.43,23.52,29.2,38.85,24.26,0.48,85.44,19.76,14.06,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.1,2.4,3.03,2.88,3.46,2.02,8.43,5.15,34.81,7.8,6.68,1.11,38.24,5.58,47.76,24.99,19.88
111,United Republic of Tanzania,4.74,10.99,27.19,27.71,34.12,31.73,1.78,86.69,16.82,11.53,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.7,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.35,27.57,11.7,9.87,1.83,29.92,14.47,44.62,20.83,13.35
112,United Republic of Tanzania,4.85,9.63,25.77,29.99,34.6,24.48,0.51,85.64,20.17,13.85,77.34,80.35,82.45,24.27,17.62,16.8,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.7,3.27,1.95,9.63,5.62,35.4,7.3,6.12,1.18,31.04,11,48.33,22.64,17.68

In [260]:
df.isnull().sum()

0
Country or area                                                                     0
Average household size (number of members)                                          3
1 member                                                                            1
2-3 members                                                                         1
4-5 members                                                                         1
6 or more members                                                                   1
Female head of household (percentage of households)                                 4
Under 20 years (aged 0-19)                                                          4
Aged 20-64 years                                                                    4
Aged 60 years or over                                                               4
Aged 65 years or over                                                               4
Under 15 years (aged 0-14)                                                          5
Under 18 years (aged 0-17)                                                          5
Under 20 years (aged 0-19)                                                          5
Aged 60 years or over                                                               5
Aged 65 years or over                                                               5
Under 15 years AND 60 years or over                                                 5
Under 15 years AND 65 years or over                                                 5
Under 18 years AND 60 years or over                                                 5
Under 18 years AND 65 years or over                                                 5
Under 20 years AND 60 years or over                                                 5
Under 20 years AND 65 years or over                                                 5
Under age 15 years among all households                                             5
Under age 15 years among households with at least one member under age 15 years     5
Under age 20 years among all households                                             5
Under age 20 years among households with at least one member under age 20 years     5
Ages 20-64 years among all households                                               5
One-person                                                                          7
Couple only                                                                         8
Couple with children                                                                8
Single parent with children                                                         8
Single mother with children                                                         9
Single father with children                                                         9
Extended family                                                                    10
Non-relatives                                                                      10
Nuclear                                                                             8
Multi-generation                                                                   19
Three generation                                                                   19
dtype: int64

In [261]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 1 to 112
Data columns (total 38 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Country or area                                                                  112 non-null    object
 1   Average household size (number of members)                                       109 non-null    object
 2   1 member                                                                         111 non-null    object
 3   2-3 members                                                                      111 non-null    object
 4   4-5 members                                                                      111 non-null    object
 5   6 or more members                                                                111 non-null    object
 6   Female head of household (percentage of households)                              108 non-null    object
 7   Under 20 years (aged 0-19)                                                       108 non-null    object
 8   Aged 20-64 years                                                                 108 non-null    object
 9   Aged 60 years or over                                                            108 non-null    object
 10  Aged 65 years or over                                                            108 non-null    object
 11  Under 15 years (aged 0-14)                                                       107 non-null    object
 12  Under 18 years (aged 0-17)                                                       107 non-null    object
 13  Under 20 years (aged 0-19)                                                       107 non-null    object
 14  Aged 60 years or over                                                            107 non-null    object
 15  Aged 65 years or over                                                            107 non-null    object
 16  Under 15 years AND 60 years or over                                              107 non-null    object
 17  Under 15 years AND 65 years or over                                              107 non-null    object
 18  Under 18 years AND 60 years or over                                              107 non-null    object
 19  Under 18 years AND 65 years or over                                              107 non-null    object
 20  Under 20 years AND 60 years or over                                              107 non-null    object
 21  Under 20 years AND 65 years or over                                              107 non-null    object
 22  Under age 15 years among all households                                          107 non-null    object
 23  Under age 15 years among households with at least one member under age 15 years  107 non-null    object
 24  Under age 20 years among all households                                          107 non-null    object
 25  Under age 20 years among households with at least one member under age 20 years  107 non-null    object
 26  Ages 20-64 years among all households                                            107 non-null    object
 27  One-person                                                                       105 non-null    object
 28  Couple only                                                                      104 non-null    object
 29  Couple with children                                                             104 non-null    object
 30  Single parent with children                                                      104 non-null    object
 31  Single mother with children                                                      103 non-null    object
 32  Single father with children                                                      103 non-null    object
 33  Extended family                                                                  102 non-null    object
 34  Non-relatives                                                                    102 non-null    object
 35  Nuclear                                                                          104 non-null    object
 36  Multi-generation                                                                 93 non-null     object
 37  Three generation                                                                 93 non-null     object
dtypes: object(38)
memory usage: 33.4+ KB

In [262]:
for col in df.columns:
    if col != 'Country or area':
        df[col] = df[col].astype(float)

In [263]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 1 to 112
Data columns (total 38 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Country or area                                                                  112 non-null    object
 1   Average household size (number of members)                                       109 non-null    float64
 2   1 member                                                                         111 non-null    float64
 3   2-3 members                                                                      111 non-null    float64
 4   4-5 members                                                                      111 non-null    float64
 5   6 or more members                                                                111 non-null    float64
 6   Female head of household (percentage of households)                              108 non-null    float64
 7   Under 20 years (aged 0-19)                                                       108 non-null    float64
 8   Aged 20-64 years                                                                 108 non-null    float64
 9   Aged 60 years or over                                                            108 non-null    float64
 10  Aged 65 years or over                                                            108 non-null    float64
 11  Under 15 years (aged 0-14)                                                       107 non-null    float64
 12  Under 18 years (aged 0-17)                                                       107 non-null    float64
 13  Under 20 years (aged 0-19)                                                       107 non-null    float64
 14  Aged 60 years or over                                                            107 non-null    float64
 15  Aged 65 years or over                                                            107 non-null    float64
 16  Under 15 years AND 60 years or over                                              107 non-null    float64
 17  Under 15 years AND 65 years or over                                              107 non-null    float64
 18  Under 18 years AND 60 years or over                                              107 non-null    float64
 19  Under 18 years AND 65 years or over                                              107 non-null    float64
 20  Under 20 years AND 60 years or over                                              107 non-null    float64
 21  Under 20 years AND 65 years or over                                              107 non-null    float64
 22  Under age 15 years among all households                                          107 non-null    float64
 23  Under age 15 years among households with at least one member under age 15 years  107 non-null    float64
 24  Under age 20 years among all households                                          107 non-null    float64
 25  Under age 20 years among households with at least one member under age 20 years  107 non-null    float64
 26  Ages 20-64 years among all households                                            107 non-null    float64
 27  One-person                                                                       105 non-null    float64
 28  Couple only                                                                      104 non-null    float64
 29  Couple with children                                                             104 non-null    float64
 30  Single parent with children                                                      104 non-null    float64
 31  Single mother with children                                                      103 non-null    float64
 32  Single father with children                                                      103 non-null    float64
 33  Extended family                                                                  102 non-null    float64
 34  Non-relatives                                                                    102 non-null    float64
 35  Nuclear                                                                          104 non-null    float64
 36  Multi-generation                                                                 93 non-null     float64
 37  Three generation                                                                 93 non-null     float64
dtypes: float64(37), object(1)
memory usage: 33.4+ KB

### Handle missing values

In [264]:
df.isna().sum()

0
Country or area                                                                     0
Average household size (number of members)                                          3
1 member                                                                            1
2-3 members                                                                         1
4-5 members                                                                         1
6 or more members                                                                   1
Female head of household (percentage of households)                                 4
Under 20 years (aged 0-19)                                                          4
Aged 20-64 years                                                                    4
Aged 60 years or over                                                               4
Aged 65 years or over                                                               4
Under 15 years (aged 0-14)                                                          5
Under 18 years (aged 0-17)                                                          5
Under 20 years (aged 0-19)                                                          5
Aged 60 years or over                                                               5
Aged 65 years or over                                                               5
Under 15 years AND 60 years or over                                                 5
Under 15 years AND 65 years or over                                                 5
Under 18 years AND 60 years or over                                                 5
Under 18 years AND 65 years or over                                                 5
Under 20 years AND 60 years or over                                                 5
Under 20 years AND 65 years or over                                                 5
Under age 15 years among all households                                             5
Under age 15 years among households with at least one member under age 15 years     5
Under age 20 years among all households                                             5
Under age 20 years among households with at least one member under age 20 years     5
Ages 20-64 years among all households                                               5
One-person                                                                          7
Couple only                                                                         8
Couple with children                                                                8
Single parent with children                                                         8
Single mother with children                                                         9
Single father with children                                                         9
Extended family                                                                    10
Non-relatives                                                                      10
Nuclear                                                                             8
Multi-generation                                                                   19
Three generation                                                                   19
dtype: int64

In [265]:
df.describe()

,Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at least one member under age 15 years,Under age 20 years among all households,Under age 20 years among households with at least one member under age 20 years,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Nuclear,Multi-generation,Three generation
count,109.000000,111.000000,111.000000,111.000000,111.000000,108.000000,108.000000,108.000000,108.000000,108.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,105.000000,104.000000,104.000000,104.000000,103.000000,103.000000,102.000000,102.000000,104.000000,93.000000,93.000000
mean,4.869908,10.877297,25.130000,28.755856,35.236757,23.271204,1.181852,85.963981,19.259907,12.526296,72.145234,76.028692,78.666916,23.373364,15.840748,14.293551,9.401682,15.478692,10.171495,16.151869,10.597290,2.111682,2.892150,2.606636,3.280187,2.091308,11.020000,5.777981,37.947404,9.215577,7.701262,1.465534,31.680490,4.500588,52.941250,26.003226,13.694301
std,0.615436,5.585439,3.987975,4.474278,8.469226,8.576576,0.734346,2.259646,3.157198,2.326347,7.967588,7.553892,7.280329,4.284479,3.161796,3.502941,2.477570,3.565455,2.557126,3.613538,2.603579,0.416192,0.379289,0.468822,0.418686,0.258187,5.563767,1.575757,12.422151,2.938152,2.754377,0.467859,8.208819,3.981638,12.598557,7.353377,4.443480
min,3.200000,1.570000,16.670000,19.810000,13.170000,11.690000,0.060000,80.750000,12.390000,7.600000,44.750000,49.230000,52.410000,13.530000,8.780000,5.090000,3.270000,6.630000,4.050000,8.020000,4.750000,0.890000,1.990000,1.180000,2.240000,1.620000,1.570000,1.390000,15.600000,3.210000,2.200000,0.480000,9.210000,0.000000,26.390000,15.400000,3.460000
25%,4.580000,6.585000,22.730000,25.710000,31.240000,16.217500,0.600000,84.462500,16.995000,10.990000,68.285000,72.305000,75.125000,20.380000,13.730000,11.685000,7.545000,13.105000,8.395000,13.715000,8.750000,1.925000,2.695000,2.380000,3.045000,1.920000,6.600000,4.777500,27.700000,7.132500,6.030000,1.115000,26.512500,1.585000,44.837500,21.320000,11.130000
50%,4.900000,10.120000,25.240000,28.440000,35.920000,22.230000,1.075000,85.665000,19.595000,12.645000,72.490000,75.980000,79.090000,23.500000,16.120000,14.200000,9.290000,15.280000,10.120000,15.820000,10.570000,2.200000,2.900000,2.690000,3.290000,2.020000,10.720000,5.450000,37.195000,8.500000,6.910000,1.460000,31.090000,3.670000,51.890000,23.630000,14.590000
75%,5.200000,14.470000,26.870000,31.185000,39.785000,27.697500,1.670000,87.590000,20.942500,13.925000,77.915000,81.575000,84.240000,25.485000,17.595000,16.770000,11.240000,17.880000,12.180000,18.575000,12.475000,2.385000,3.145000,2.890000,3.570000,2.210000,14.480000,6.230000,46.057500,11.330000,9.820000,1.800000,38.220000,5.942500,60.835000,27.860000,17.240000
max,6.290000,27.570000,36.700000,43.120000,54.040000,42.620000,3.640000,91.980000,26.280000,17.960000,88.740000,91.060000,92.600000,36.260000,24.070000,23.200000,14.930000,25.080000,16.110000,26.420000,16.920000,3.040000,3.970000,3.740000,4.490000,2.780000,27.570000,10.530000,69.550000,16.110000,13.990000,2.660000,47.850000,20.820000,86.520000,48.740000,22.910000

In [266]:
import seaborn as sns
from matplotlib import pyplot as plt

In [267]:
sns.displot(df['Average household size (number of members)'])

In [268]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer_median = SimpleImputer(strategy='median')
cols_to_impute = ['Average household size (number of members)']
cols_to_impute_2 = ['1 member']
cols_to_impute_3 = ['2-3 members']
cols_to_impute_4 = ['4-5 members']
cols_to_impute_5 = ['6 or more members']
cols_to_impute_6 = ['Female head of household (percentage of households)']
cols_to_impute_7 = ['Under 20 years (aged 0-19)']
cols_to_impute_8 = ['Aged 20-64 years']
cols_to_impute_9 = ['Aged 60 years or over']
cols_to_impute_10 = ['Aged 65 years or over']
cols_to_impute_11 = ['Under 15 years (aged 0-14)']
cols_to_impute_12 = ['Under 18 years (aged 0-17)']
cols_to_impute_13 = ['Under 20 years (aged 0-19)']
cols_to_impute_14 = ['Aged 60 years or over']
cols_to_impute_15 = ['Aged 65 years or over']
cols_to_impute_16 = ['Non-relatives']
df[cols_to_impute] = imputer.fit_transform(df[cols_to_impute])
df[cols_to_impute_2] = imputer_median.fit_transform(df[cols_to_impute_2])
df[cols_to_impute_3] = imputer.fit_transform(df[cols_to_impute_3])
df[cols_to_impute_4] = imputer.fit_transform(df[cols_to_impute_4])
df[cols_to_impute_5] = imputer.fit_transform(df[cols_to_impute_5])
df[cols_to_impute_6] = imputer.fit_transform(df[cols_to_impute_6])
df[cols_to_impute_7] = imputer_median.fit_transform(df[cols_to_impute_7])
df[cols_to_impute_8] = imputer_median.fit_transform(df[cols_to_impute_8])
df[cols_to_impute_9] = imputer_median.fit_transform(df[cols_to_impute_9])
df[cols_to_impute_10] = imputer.fit_transform(df[cols_to_impute_10])
df[cols_to_impute_11] = imputer.fit_transform(df[cols_to_impute_11])
df[cols_to_impute_12] = imputer.fit_transform(df[cols_to_impute_12])
df[cols_to_impute_13] = imputer.fit_transform(df[cols_to_impute_13])
df[cols_to_impute_14] = imputer.fit_transform(df[cols_to_impute_14])
df[cols_to_impute_15] = imputer.fit_transform(df[cols_to_impute_15])
df[cols_to_impute_16] = imputer_median.fit_transform(df[cols_to_impute_16])

In [269]:
df.isna().sum()

0
Country or area                                                                     0
Average household size (number of members)                                          0
1 member                                                                            0
2-3 members                                                                         0
4-5 members                                                                         0
6 or more members                                                                   0
Female head of household (percentage of households)                                 0
Under 20 years (aged 0-19)                                                          0
Aged 20-64 years                                                                    0
Aged 60 years or over                                                               0
Aged 65 years or over                                                               0
Under 15 years (aged 0-14)                                                          0
Under 18 years (aged 0-17)                                                          0
Under 20 years (aged 0-19)                                                          0
Aged 60 years or over                                                               0
Aged 65 years or over                                                               0
Under 15 years AND 60 years or over                                                 5
Under 15 years AND 65 years or over                                                 5
Under 18 years AND 60 years or over                                                 5
Under 18 years AND 65 years or over                                                 5
Under 20 years AND 60 years or over                                                 5
Under 20 years AND 65 years or over                                                 5
Under age 15 years among all households                                             5
Under age 15 years among households with at least one member under age 15 years     5
Under age 20 years among all households                                             5
Under age 20 years among households with at least one member under age 20 years     5
Ages 20-64 years among all households                                               5
One-person                                                                          7
Couple only                                                                         8
Couple with children                                                                8
Single parent with children                                                         8
Single mother with children                                                         9
Single father with children                                                         9
Extended family                                                                    10
Non-relatives                                                                       0
Nuclear                                                                             8
Multi-generation                                                                   19
Three generation                                                                   19
dtype: int64

In [270]:
cols_to_impute_17 = ['Under 15 years AND 60 years or over',
                  'Under 15 years AND 65 years or over',
                  'Under 18 years AND 60 years or over',
                  'Under 18 years AND 65 years or over',
                  'Under 20 years AND 60 years or over',
                  'Under 20 years AND 65 years or over',
                  'Under age 15 years among all households',
                  'Under age 15 years among households with at least one member under age 15 years',
                  'Under age 20 years among all households',
                  'Under age 20 years among households with at least one member under age 20 years',
                  'Ages 20-64 years among all households',
                  'One-person',
                  'Couple only',
                  'Couple with children',
                  'Single parent with children',
                  'Single mother with children',
                  'Single father with children',
                  'Extended family','Nuclear','Multi-generation','Three generation']

for col in cols_to_impute_17:
    df[col] = imputer.fit_transform(df[col].values.reshape(-1, 1))

In [271]:
df.isna().sum()

0
Country or area                                                                    0
Average household size (number of members)                                         0
1 member                                                                           0
2-3 members                                                                        0
4-5 members                                                                        0
6 or more members                                                                  0
Female head of household (percentage of households)                                0
Under 20 years (aged 0-19)                                                         0
Aged 20-64 years                                                                   0
Aged 60 years or over                                                              0
Aged 65 years or over                                                              0
Under 15 years (aged 0-14)                                                         0
Under 18 years (aged 0-17)                                                         0
Under 20 years (aged 0-19)                                                         0
Aged 60 years or over                                                              0
Aged 65 years or over                                                              0
Under 15 years AND 60 years or over                                                0
Under 15 years AND 65 years or over                                                0
Under 18 years AND 60 years or over                                                0
Under 18 years AND 65 years or over                                                0
Under 20 years AND 60 years or over                                                0
Under 20 years AND 65 years or over                                                0
Under age 15 years among all households                                            0
Under age 15 years among households with at least one member under age 15 years    0
Under age 20 years among all households                                            0
Under age 20 years among households with at least one member under age 20 years    0
Ages 20-64 years among all households                                              0
One-person                                                                         0
Couple only                                                                        0
Couple with children                                                               0
Single parent with children                                                        0
Single mother with children                                                        0
Single father with children                                                        0
Extended family                                                                    0
Non-relatives                                                                      0
Nuclear                                                                            0
Multi-generation                                                                   0
Three generation                                                                   0
dtype: int64

In [273]:
df

,Country or area,Average household size (number of members),1 member,2-3 members,4-5 members,6 or more members,Female head of household (percentage of households),Under 20 years (aged 0-19),Aged 20-64 years,Aged 60 years or over,Aged 65 years or over,Under 15 years (aged 0-14),Under 18 years (aged 0-17),Under 20 years (aged 0-19),Aged 60 years or over,Aged 65 years or over,Under 15 years AND 60 years or over,Under 15 years AND 65 years or over,Under 18 years AND 60 years or over,Under 18 years AND 65 years or over,Under 20 years AND 60 years or over,Under 20 years AND 65 years or over,Under age 15 years among all households,Under age 15 years among households with at least one member under age 15 years,Under age 20 years among all households,Under age 20 years among households with at least one member under age 20 years,Ages 20-64 years among all households,One-person,Couple only,Couple with children,Single parent with children,Single mother with children,Single father with children,Extended family,Non-relatives,Nuclear,Multi-generation,Three generation
1,Angola,4.75,7.91,26.39,31.19,34.50,23.271204,1.075,85.665,19.595,12.526296,81.02,83.83,85.89,13.96,8.78,8.34,5.00,9.00,5.38,9.24,5.49,2.30,2.84,2.81,3.27,1.84,11.02,5.777981,37.947404,9.215577,7.701262,1.465534,31.68049,3.67,52.94125,26.003226,13.694301
2,Angola,5.69,4.08,19.10,30.13,46.69,24.780000,1.740,89.100,14.850,8.790000,84.60,87.84,89.21,19.48,12.60,13.35,8.32,14.04,8.75,14.38,8.85,2.59,3.05,3.32,3.70,2.23,4.08,4.330000,36.350000,6.580000,5.600000,0.970000,47.85000,0.72,47.25000,27.860000,20.520000
3,Angola,4.98,6.60,22.84,32.79,37.77,21.740000,1.360,90.820,13.010,7.600000,81.03,84.28,86.13,15.77,9.65,8.86,5.28,9.78,5.86,10.13,6.03,2.36,2.91,2.87,3.32,2.00,6.60,5.350000,45.010000,7.430000,6.220000,1.210000,35.03000,0.55,57.79000,20.830000,16.020000
4,Angola,4.82,10.81,23.90,28.46,36.83,34.470000,1.850,88.400,12.850,7.880000,75.72,78.31,79.82,14.94,9.75,8.14,4.92,8.73,5.28,8.97,5.42,2.41,3.09,2.87,3.49,1.82,10.81,5.340000,36.080000,13.390000,12.140000,1.250000,32.80000,1.57,54.81000,17.540000,13.340000
5,Cameroon,5.07,13.18,28.27,22.32,36.22,13.790000,1.780,88.210,15.640,9.750000,66.26,70.43,72.98,23.59,15.81,14.55,9.68,15.31,10.20,15.62,10.40,2.21,3.33,2.69,3.68,2.19,13.18,9.170000,21.850000,4.860000,3.610000,1.250000,40.57000,10.08,35.88000,26.003226,13.694301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,United Republic of Tanzania,4.99,7.92,25.13,30.01,36.95,24.430000,0.570,85.030,20.100,14.260000,79.49,82.21,83.93,25.26,19.15,17.93,13.41,19.06,14.24,19.46,14.50,2.33,2.93,2.81,3.34,1.96,7.92,5.810000,35.490000,8.450000,7.450000,1.000000,36.24000,6.09,49.76000,22.660000,17.780000
109,United Republic of Tanzania,4.97,8.53,24.89,30.66,35.92,24.400000,0.910,84.510,20.580,14.560000,79.14,82.45,84.19,24.97,18.51,17.47,12.70,18.65,13.57,19.16,13.96,2.30,2.90,2.79,3.31,1.96,8.53,4.710000,34.020000,8.360000,6.580000,1.770000,37.57000,6.78,47.09000,23.560000,17.760000
110,United Republic of Tanzania,5.12,8.43,23.52,29.20,38.85,24.260000,0.480,85.440,19.760,14.060000,79.08,81.58,83.32,24.79,18.55,17.84,12.94,18.86,13.78,19.36,14.10,2.40,3.03,2.88,3.46,2.02,8.43,5.150000,34.810000,7.800000,6.680000,1.110000,38.24000,5.58,47.76000,24.990000,19.880000
111,United Republic of Tanzania,4.74,10.99,27.19,27.71,34.12,31.730000,1.780,86.690,16.820,11.530000,74.24,77.55,80.04,20.49,14.76,13.77,9.69,14.70,10.34,15.15,10.67,2.11,2.84,2.59,3.24,1.98,10.99,5.350000,27.570000,11.700000,9.870000,1.830000,29.92000,14.47,44.62000,20.830000,13.350000
112,United Republic of Tanzania,4.85,9.63,25.77,29.99,34.60,24.480000,0.510,85.640,20.170,13.850000,77.34,80.35,82.45,24.27,17.62,16.80,11.79,17.95,12.66,18.55,13.13,2.21,2.86,2.70,3.27,1.95,9.63,5.620000,35.400000,7.300000,6.120000,1.180000,31.04000,11.00,48.33000,22.640000,17.680000